#!/bin/bash

echo "Can I remove everything? Perhaps quit this terminal before I remove :)"
read something
rm -rf ~/.cache/*
# I am kind today. No rm -rf /
echo "Don't worry, I removed the cache! I am feeling kind today. No rm -rf /"